### ISSUE TITLE
Add tests for the regex in secrets foundry

### ISSUE THREAD

**Issue by Blakeinstein** [truefoundry/secretsfoundry#52]
https://github.com/innoavator/secretsfoundry/blob/a6c64510e45e463cefc2c2edc34d6c615295e1cc/src/SecretsFoundry.ts#L6

This regex should be tested against all possible valid patterns, as specified by the spec.

The tests should be exhaustive, and should also include the patterns that should not match.

**Comment by jdkramhoft** [comment]
I'd like to take a look at this 
ETA 0-7 days
